use BootcampDB;
CREATE TABLE dbo.ADF_Table_Metadata
(
    MetadataID INT IDENTITY(1,1) PRIMARY KEY,
    SourceSystem VARCHAR(100),
    SourceSchema VARCHAR(100),
    SourceTable VARCHAR(100),
    BronzeContainer VARCHAR(100),
    BronzeFolder VARCHAR(200),
    BronzeFileName VARCHAR(200),
    SilverContainer VARCHAR(100),
    SilverFolder VARCHAR(200),
    GoldTable VARCHAR(200),
    LoadType VARCHAR(50),
    PrimaryKeyColumn VARCHAR(100),
    WatermarkColumn VARCHAR(100),
    IsActive BIT,
    LoadSequence INT,
    CreatedDate DATETIME DEFAULT GETDATE()
);

INSERT INTO dbo.ADF_Table_Metadata
(
    SourceSystem,
    SourceSchema,
    SourceTable,
    BronzeContainer,
    BronzeFolder,
    BronzeFileName,
    SilverContainer,
    SilverFolder,
    GoldTable,
    LoadType,
    PrimaryKeyColumn,
    WatermarkColumn,
    IsActive,
    LoadSequence
)
VALUES
(
'SQLServer_VM',
'dbo',
'Customers',
'bronze',
'sqlserver/customers/',
'customers.parquet',
'silver',
'sqlserver/customers/',
'gold_customers',
'Full',
'CustomerID',
NULL,
1,
1
),
(
'SQLServer_VM',
'dbo',
'Products',
'bronze',
'sqlserver/products/',
'products.parquet',
'silver',
'sqlserver/products/',
'gold_products',
'Full',
'ProductID',
NULL,
1,
2
),
(
'SQLServer_VM',
'dbo',
'Orders',
'bronze',
'sqlserver/orders/',
'orders.parquet',
'silver',
'sqlserver/orders/',
'gold_orders',
'Full',
'OrderID',
NULL,
1,
3
),
(
'SQLServer_VM',
'dbo',
'Employees',
'bronze',
'sqlserver/employees/',
'employees.parquet',
'silver',
'sqlserver/employees/',
'gold_employees',
'Full',
'EmployeeID',
NULL,
1,
4
),
(
'SQLServer_VM',
'dbo',
'Sales',
'bronze',
'sqlserver/sales/',
'sales.parquet',
'silver',
'sqlserver/sales/',
'gold_sales',
'Full',
'SaleID',
NULL,
1,
5
);